FROM node:8-stretch


ENV PORT 3000
ENV NODE_HEAPDUMP_OPTIONS nosignal

EXPOSE 3000
EXPOSE 9229

WORKDIR "/app"

# Bundle app source
COPY . /app
COPY run-dev /bin
COPY run-debug /bin
RUN chmod 777 /bin/run-dev /bin/run-debug
RUN apt-get update
RUN apt-get install bc

CMD ["/bin/bash"]


